/*
 * This file is generated by jOOQ.
 */
package org.poem.entities;


import org.poem.entities.tables.DsgGatherDb;
import org.poem.entities.tables.DsgGatherInfo;
import org.poem.entities.tables.DsgGatherTable;
import org.poem.entities.tables.DsgGatherTableFields;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in kylo
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.11.9"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Tables {

    /**
     * 元数据数据库信息
     */
    public static final DsgGatherDb DSG_GATHER_DB = org.poem.entities.tables.DsgGatherDb.DSG_GATHER_DB;

    /**
     * 元数据采集信息
     */
    public static final DsgGatherInfo DSG_GATHER_INFO = org.poem.entities.tables.DsgGatherInfo.DSG_GATHER_INFO;

    /**
     * 元数据数据表信息
     */
    public static final DsgGatherTable DSG_GATHER_TABLE = org.poem.entities.tables.DsgGatherTable.DSG_GATHER_TABLE;

    /**
     * 元数据表信息
     */
    public static final DsgGatherTableFields DSG_GATHER_TABLE_FIELDS = org.poem.entities.tables.DsgGatherTableFields.DSG_GATHER_TABLE_FIELDS;
}
