/*
 * This file is generated by jOOQ.
 */
package org.poem.entities.tables.records;


import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.UpdatableRecordImpl;
import org.poem.entities.tables.DsgGatherTableFields;

import javax.annotation.Generated;
import java.sql.Timestamp;


/**
 * 元数据表信息
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.11.9"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class DsgGatherTableFieldsRecord extends UpdatableRecordImpl<DsgGatherTableFieldsRecord> implements Record8<String, String, String, String, String, String, Timestamp, Timestamp> {

    private static final long serialVersionUID = 494482272;

    /**
     * Create a detached DsgGatherTableFieldsRecord
     */
    public DsgGatherTableFieldsRecord() {
        super( DsgGatherTableFields.DSG_GATHER_TABLE_FIELDS );
    }

    /**
     * Create a detached, initialised DsgGatherTableFieldsRecord
     */
    public DsgGatherTableFieldsRecord(String id, String gatherTableId, String field, String dataType, String description, String defaultValue, Timestamp createTime, Timestamp updateTime) {
        super( DsgGatherTableFields.DSG_GATHER_TABLE_FIELDS );

        set( 0, id );
        set( 1, gatherTableId );
        set( 2, field );
        set( 3, dataType );
        set( 4, description );
        set( 5, defaultValue );
        set( 6, createTime );
        set( 7, updateTime );
    }

    /**
     * Getter for <code>kylo.dsg_gather_table_fields.id</code>. id
     */
    public String getId() {
        return (String) get( 0 );
    }

    /**
     * Setter for <code>kylo.dsg_gather_table_fields.id</code>. id
     */
    public void setId(String value) {
        set( 0, value );
    }

    /**
     * Getter for <code>kylo.dsg_gather_table_fields.gather_table_id</code>. 表
     */
    public String getGatherTableId() {
        return (String) get( 1 );
    }

    /**
     * Setter for <code>kylo.dsg_gather_table_fields.gather_table_id</code>. 表
     */
    public void setGatherTableId(String value) {
        set( 1, value );
    }

    /**
     * Getter for <code>kylo.dsg_gather_table_fields.field</code>. 字段
     */
    public String getField() {
        return (String) get( 2 );
    }

    /**
     * Setter for <code>kylo.dsg_gather_table_fields.field</code>. 字段
     */
    public void setField(String value) {
        set( 2, value );
    }

    /**
     * Getter for <code>kylo.dsg_gather_table_fields.data_type</code>. 数据类型
     */
    public String getDataType() {
        return (String) get( 3 );
    }

    /**
     * Setter for <code>kylo.dsg_gather_table_fields.data_type</code>. 数据类型
     */
    public void setDataType(String value) {
        set( 3, value );
    }

    /**
     * Getter for <code>kylo.dsg_gather_table_fields.description</code>. 描述
     */
    public String getDescription() {
        return (String) get( 4 );
    }

    /**
     * Setter for <code>kylo.dsg_gather_table_fields.description</code>. 描述
     */
    public void setDescription(String value) {
        set( 4, value );
    }

    /**
     * Getter for <code>kylo.dsg_gather_table_fields.default_value</code>. 默认值
     */
    public String getDefaultValue() {
        return (String) get( 5 );
    }

    /**
     * Setter for <code>kylo.dsg_gather_table_fields.default_value</code>. 默认值
     */
    public void setDefaultValue(String value) {
        set( 5, value );
    }

    /**
     * Getter for <code>kylo.dsg_gather_table_fields.create_time</code>.
     */
    public Timestamp getCreateTime() {
        return (Timestamp) get( 6 );
    }

    /**
     * Setter for <code>kylo.dsg_gather_table_fields.create_time</code>.
     */
    public void setCreateTime(Timestamp value) {
        set( 6, value );
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * Getter for <code>kylo.dsg_gather_table_fields.update_time</code>.
     */
    public Timestamp getUpdateTime() {
        return (Timestamp) get( 7 );
    }

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    /**
     * Setter for <code>kylo.dsg_gather_table_fields.update_time</code>.
     */
    public void setUpdateTime(Timestamp value) {
        set( 7, value );
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<String, String, String, String, String, String, Timestamp, Timestamp> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<String, String, String, String, String, String, Timestamp, Timestamp> valuesRow() {
        return (Row8) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return DsgGatherTableFields.DSG_GATHER_TABLE_FIELDS.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return DsgGatherTableFields.DSG_GATHER_TABLE_FIELDS.GATHER_TABLE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return DsgGatherTableFields.DSG_GATHER_TABLE_FIELDS.FIELD;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return DsgGatherTableFields.DSG_GATHER_TABLE_FIELDS.DATA_TYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return DsgGatherTableFields.DSG_GATHER_TABLE_FIELDS.DESCRIPTION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return DsgGatherTableFields.DSG_GATHER_TABLE_FIELDS.DEFAULT_VALUE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field7() {
        return DsgGatherTableFields.DSG_GATHER_TABLE_FIELDS.CREATE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field8() {
        return DsgGatherTableFields.DSG_GATHER_TABLE_FIELDS.UPDATE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getGatherTableId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getField();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getDataType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getDescription();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getDefaultValue();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component7() {
        return getCreateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component8() {
        return getUpdateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getGatherTableId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getField();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getDataType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getDescription();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getDefaultValue();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value7() {
        return getCreateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value8() {
        return getUpdateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DsgGatherTableFieldsRecord value1(String value) {
        setId( value );
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DsgGatherTableFieldsRecord value2(String value) {
        setGatherTableId( value );
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DsgGatherTableFieldsRecord value3(String value) {
        setField( value );
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DsgGatherTableFieldsRecord value4(String value) {
        setDataType( value );
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DsgGatherTableFieldsRecord value5(String value) {
        setDescription( value );
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DsgGatherTableFieldsRecord value6(String value) {
        setDefaultValue( value );
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DsgGatherTableFieldsRecord value7(Timestamp value) {
        setCreateTime( value );
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public DsgGatherTableFieldsRecord value8(Timestamp value) {
        setUpdateTime( value );
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DsgGatherTableFieldsRecord values(String value1, String value2, String value3, String value4, String value5, String value6, Timestamp value7, Timestamp value8) {
        value1( value1 );
        value2( value2 );
        value3( value3 );
        value4( value4 );
        value5( value5 );
        value6( value6 );
        value7( value7 );
        value8( value8 );
        return this;
    }
}
