/*
 * This file is generated by jOOQ.
 */
package org.poem.entities.tables.records;


import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;
import org.poem.entities.tables.DsgGatherStatistics;


/**
 * 采集表信息
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DsgGatherStatisticsRecord extends UpdatableRecordImpl<DsgGatherStatisticsRecord> implements Record7<String, String, Integer, Integer, Integer, Timestamp, Timestamp> {

    private static final long serialVersionUID = 2137671987;

    /**
     * Setter for <code>kylo.dsg_gather_statistics.id</code>. id
     */
    public void setId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>kylo.dsg_gather_statistics.id</code>. id
     */
    public String getId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>kylo.dsg_gather_statistics.gather_info_id</code>. 元数据信息, 和任务在一起
     */
    public void setGatherInfoId(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>kylo.dsg_gather_statistics.gather_info_id</code>. 元数据信息, 和任务在一起
     */
    public String getGatherInfoId() {
        return (String) get(1);
    }

    /**
     * Setter for <code>kylo.dsg_gather_statistics.gather_db_count</code>. 抓取的数据库数量
     */
    public void setGatherDbCount(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>kylo.dsg_gather_statistics.gather_db_count</code>. 抓取的数据库数量
     */
    public Integer getGatherDbCount() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>kylo.dsg_gather_statistics.gather_table_count</code>. 抓取的表的个数
     */
    public void setGatherTableCount(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>kylo.dsg_gather_statistics.gather_table_count</code>. 抓取的表的个数
     */
    public Integer getGatherTableCount() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>kylo.dsg_gather_statistics.gather_field_count</code>. 抓取的表列的个数
     */
    public void setGatherFieldCount(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>kylo.dsg_gather_statistics.gather_field_count</code>. 抓取的表列的个数
     */
    public Integer getGatherFieldCount() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>kylo.dsg_gather_statistics.create_time</code>.
     */
    public void setCreateTime(Timestamp value) {
        set(5, value);
    }

    /**
     * Getter for <code>kylo.dsg_gather_statistics.create_time</code>.
     */
    public Timestamp getCreateTime() {
        return (Timestamp) get(5);
    }

    /**
     * Setter for <code>kylo.dsg_gather_statistics.update_time</code>.
     */
    public void setUpdateTime(Timestamp value) {
        set(6, value);
    }

    /**
     * Getter for <code>kylo.dsg_gather_statistics.update_time</code>.
     */
    public Timestamp getUpdateTime() {
        return (Timestamp) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<String, String, Integer, Integer, Integer, Timestamp, Timestamp> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<String, String, Integer, Integer, Integer, Timestamp, Timestamp> valuesRow() {
        return (Row7) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return DsgGatherStatistics.DSG_GATHER_STATISTICS.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return DsgGatherStatistics.DSG_GATHER_STATISTICS.GATHER_INFO_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return DsgGatherStatistics.DSG_GATHER_STATISTICS.GATHER_DB_COUNT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return DsgGatherStatistics.DSG_GATHER_STATISTICS.GATHER_TABLE_COUNT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field5() {
        return DsgGatherStatistics.DSG_GATHER_STATISTICS.GATHER_FIELD_COUNT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field6() {
        return DsgGatherStatistics.DSG_GATHER_STATISTICS.CREATE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field7() {
        return DsgGatherStatistics.DSG_GATHER_STATISTICS.UPDATE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getGatherInfoId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component3() {
        return getGatherDbCount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component4() {
        return getGatherTableCount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component5() {
        return getGatherFieldCount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component6() {
        return getCreateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component7() {
        return getUpdateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getGatherInfoId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getGatherDbCount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getGatherTableCount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value5() {
        return getGatherFieldCount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value6() {
        return getCreateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value7() {
        return getUpdateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DsgGatherStatisticsRecord value1(String value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DsgGatherStatisticsRecord value2(String value) {
        setGatherInfoId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DsgGatherStatisticsRecord value3(Integer value) {
        setGatherDbCount(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DsgGatherStatisticsRecord value4(Integer value) {
        setGatherTableCount(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DsgGatherStatisticsRecord value5(Integer value) {
        setGatherFieldCount(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DsgGatherStatisticsRecord value6(Timestamp value) {
        setCreateTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DsgGatherStatisticsRecord value7(Timestamp value) {
        setUpdateTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DsgGatherStatisticsRecord values(String value1, String value2, Integer value3, Integer value4, Integer value5, Timestamp value6, Timestamp value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached DsgGatherStatisticsRecord
     */
    public DsgGatherStatisticsRecord() {
        super(DsgGatherStatistics.DSG_GATHER_STATISTICS);
    }

    /**
     * Create a detached, initialised DsgGatherStatisticsRecord
     */
    public DsgGatherStatisticsRecord(String id, String gatherInfoId, Integer gatherDbCount, Integer gatherTableCount, Integer gatherFieldCount, Timestamp createTime, Timestamp updateTime) {
        super(DsgGatherStatistics.DSG_GATHER_STATISTICS);

        set(0, id);
        set(1, gatherInfoId);
        set(2, gatherDbCount);
        set(3, gatherTableCount);
        set(4, gatherFieldCount);
        set(5, createTime);
        set(6, updateTime);
    }
}
