/*
 * This file is generated by jOOQ.
 */
package org.poem.entities.tables.records;


import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record11;
import org.jooq.Row11;
import org.jooq.impl.UpdatableRecordImpl;
import org.poem.entities.tables.DsgGatherInfo;

import javax.annotation.Generated;
import java.sql.Timestamp;


/**
 * 元数据采集信息
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.11.9"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class DsgGatherInfoRecord extends UpdatableRecordImpl<DsgGatherInfoRecord> implements Record11<String, String, String, String, String, String, String, String, Byte, Timestamp, Timestamp> {

    private static final long serialVersionUID = 1295313764;

    /**
     * Create a detached DsgGatherInfoRecord
     */
    public DsgGatherInfoRecord() {
        super( DsgGatherInfo.DSG_GATHER_INFO );
    }

    /**
     * Create a detached, initialised DsgGatherInfoRecord
     */
    public DsgGatherInfoRecord(String id, String name, String ip, String port, String user, String password, String type, String remark, Byte delete, Timestamp createTime, Timestamp updateTime) {
        super( DsgGatherInfo.DSG_GATHER_INFO );

        set( 0, id );
        set( 1, name );
        set( 2, ip );
        set( 3, port );
        set( 4, user );
        set( 5, password );
        set( 6, type );
        set( 7, remark );
        set( 8, delete );
        set( 9, createTime );
        set( 10, updateTime );
    }

    /**
     * Getter for <code>kylo.dsg_gather_info.id</code>. id
     */
    public String getId() {
        return (String) get( 0 );
    }

    /**
     * Setter for <code>kylo.dsg_gather_info.id</code>. id
     */
    public void setId(String value) {
        set( 0, value );
    }

    /**
     * Getter for <code>kylo.dsg_gather_info.name</code>. 连接的名字
     */
    public String getName() {
        return (String) get( 1 );
    }

    /**
     * Setter for <code>kylo.dsg_gather_info.name</code>. 连接的名字
     */
    public void setName(String value) {
        set( 1, value );
    }

    /**
     * Getter for <code>kylo.dsg_gather_info.ip</code>. 连接ip
     */
    public String getIp() {
        return (String) get( 2 );
    }

    /**
     * Setter for <code>kylo.dsg_gather_info.ip</code>. 连接ip
     */
    public void setIp(String value) {
        set( 2, value );
    }

    /**
     * Getter for <code>kylo.dsg_gather_info.port</code>. 连接的端口
     */
    public String getPort() {
        return (String) get( 3 );
    }

    /**
     * Setter for <code>kylo.dsg_gather_info.port</code>. 连接的端口
     */
    public void setPort(String value) {
        set( 3, value );
    }

    /**
     * Getter for <code>kylo.dsg_gather_info.user</code>. 数据库连接的用户名字
     */
    public String getUser() {
        return (String) get( 4 );
    }

    /**
     * Setter for <code>kylo.dsg_gather_info.user</code>. 数据库连接的用户名字
     */
    public void setUser(String value) {
        set( 4, value );
    }

    /**
     * Getter for <code>kylo.dsg_gather_info.password</code>. 数据库连接的密码
     */
    public String getPassword() {
        return (String) get( 5 );
    }

    /**
     * Setter for <code>kylo.dsg_gather_info.password</code>. 数据库连接的密码
     */
    public void setPassword(String value) {
        set( 5, value );
    }

    /**
     * Getter for <code>kylo.dsg_gather_info.type</code>. 数据库类型 mysql或者是 orcale
     */
    public String getType() {
        return (String) get( 6 );
    }

    /**
     * Setter for <code>kylo.dsg_gather_info.type</code>. 数据库类型 mysql或者是 orcale
     */
    public void setType(String value) {
        set( 6, value );
    }

    /**
     * Getter for <code>kylo.dsg_gather_info.remark</code>. 描述
     */
    public String getRemark() {
        return (String) get( 7 );
    }

    /**
     * Setter for <code>kylo.dsg_gather_info.remark</code>. 描述
     */
    public void setRemark(String value) {
        set( 7, value );
    }

    /**
     * Getter for <code>kylo.dsg_gather_info.delete</code>. 是否删除
     */
    public Byte getDelete() {
        return (Byte) get( 8 );
    }

    /**
     * Setter for <code>kylo.dsg_gather_info.delete</code>. 是否删除
     */
    public void setDelete(Byte value) {
        set( 8, value );
    }

    /**
     * Getter for <code>kylo.dsg_gather_info.create_time</code>.
     */
    public Timestamp getCreateTime() {
        return (Timestamp) get( 9 );
    }

    /**
     * Setter for <code>kylo.dsg_gather_info.create_time</code>.
     */
    public void setCreateTime(Timestamp value) {
        set( 9, value );
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * Getter for <code>kylo.dsg_gather_info.update_time</code>.
     */
    public Timestamp getUpdateTime() {
        return (Timestamp) get( 10 );
    }

    // -------------------------------------------------------------------------
    // Record11 type implementation
    // -------------------------------------------------------------------------

    /**
     * Setter for <code>kylo.dsg_gather_info.update_time</code>.
     */
    public void setUpdateTime(Timestamp value) {
        set( 10, value );
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row11<String, String, String, String, String, String, String, String, Byte, Timestamp, Timestamp> fieldsRow() {
        return (Row11) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row11<String, String, String, String, String, String, String, String, Byte, Timestamp, Timestamp> valuesRow() {
        return (Row11) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return DsgGatherInfo.DSG_GATHER_INFO.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return DsgGatherInfo.DSG_GATHER_INFO.NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return DsgGatherInfo.DSG_GATHER_INFO.IP;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return DsgGatherInfo.DSG_GATHER_INFO.PORT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return DsgGatherInfo.DSG_GATHER_INFO.USER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return DsgGatherInfo.DSG_GATHER_INFO.PASSWORD;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return DsgGatherInfo.DSG_GATHER_INFO.TYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return DsgGatherInfo.DSG_GATHER_INFO.REMARK;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field9() {
        return DsgGatherInfo.DSG_GATHER_INFO.DELETE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field10() {
        return DsgGatherInfo.DSG_GATHER_INFO.CREATE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field11() {
        return DsgGatherInfo.DSG_GATHER_INFO.UPDATE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getIp();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getPort();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getUser();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getPassword();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component7() {
        return getType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component8() {
        return getRemark();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte component9() {
        return getDelete();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component10() {
        return getCreateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component11() {
        return getUpdateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getIp();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getPort();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getUser();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getPassword();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getRemark();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value9() {
        return getDelete();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value10() {
        return getCreateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value11() {
        return getUpdateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DsgGatherInfoRecord value1(String value) {
        setId( value );
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DsgGatherInfoRecord value2(String value) {
        setName( value );
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DsgGatherInfoRecord value3(String value) {
        setIp( value );
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DsgGatherInfoRecord value4(String value) {
        setPort( value );
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DsgGatherInfoRecord value5(String value) {
        setUser( value );
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DsgGatherInfoRecord value6(String value) {
        setPassword( value );
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DsgGatherInfoRecord value7(String value) {
        setType( value );
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DsgGatherInfoRecord value8(String value) {
        setRemark( value );
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DsgGatherInfoRecord value9(Byte value) {
        setDelete( value );
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DsgGatherInfoRecord value10(Timestamp value) {
        setCreateTime( value );
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public DsgGatherInfoRecord value11(Timestamp value) {
        setUpdateTime( value );
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DsgGatherInfoRecord values(String value1, String value2, String value3, String value4, String value5, String value6, String value7, String value8, Byte value9, Timestamp value10, Timestamp value11) {
        value1( value1 );
        value2( value2 );
        value3( value3 );
        value4( value4 );
        value5( value5 );
        value6( value6 );
        value7( value7 );
        value8( value8 );
        value9( value9 );
        value10( value10 );
        value11( value11 );
        return this;
    }
}
