/*
 * This file is generated by jOOQ.
 */
package org.poem.entities.tables.records;


import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;
import org.poem.entities.tables.DsgGatherTable;


/**
 * 采集表信息
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DsgGatherTableRecord extends UpdatableRecordImpl<DsgGatherTableRecord> implements Record7<String, String, String, String, String, Timestamp, Timestamp> {

    private static final long serialVersionUID = -486210454;

    /**
     * Setter for <code>kylo.dsg_gather_table.id</code>. id
     */
    public void setId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>kylo.dsg_gather_table.id</code>. id
     */
    public String getId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>kylo.dsg_gather_table.gather_db_id</code>. 元数据数据库信息
     */
    public void setGatherDbId(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>kylo.dsg_gather_table.gather_db_id</code>. 元数据数据库信息
     */
    public String getGatherDbId() {
        return (String) get(1);
    }

    /**
     * Setter for <code>kylo.dsg_gather_table.table</code>. 数据库表
     */
    public void setTable_(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>kylo.dsg_gather_table.table</code>. 数据库表
     */
    public String getTable_() {
        return (String) get(2);
    }

    /**
     * Setter for <code>kylo.dsg_gather_table.table_name</code>. 数据库表名字
     */
    public void setTableName(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>kylo.dsg_gather_table.table_name</code>. 数据库表名字
     */
    public String getTableName() {
        return (String) get(3);
    }

    /**
     * Setter for <code>kylo.dsg_gather_table.comment</code>. 描述
     */
    public void setComment(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>kylo.dsg_gather_table.comment</code>. 描述
     */
    public String getComment() {
        return (String) get(4);
    }

    /**
     * Setter for <code>kylo.dsg_gather_table.create_time</code>.
     */
    public void setCreateTime(Timestamp value) {
        set(5, value);
    }

    /**
     * Getter for <code>kylo.dsg_gather_table.create_time</code>.
     */
    public Timestamp getCreateTime() {
        return (Timestamp) get(5);
    }

    /**
     * Setter for <code>kylo.dsg_gather_table.update_time</code>.
     */
    public void setUpdateTime(Timestamp value) {
        set(6, value);
    }

    /**
     * Getter for <code>kylo.dsg_gather_table.update_time</code>.
     */
    public Timestamp getUpdateTime() {
        return (Timestamp) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<String, String, String, String, String, Timestamp, Timestamp> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<String, String, String, String, String, Timestamp, Timestamp> valuesRow() {
        return (Row7) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return DsgGatherTable.DSG_GATHER_TABLE.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return DsgGatherTable.DSG_GATHER_TABLE.GATHER_DB_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return DsgGatherTable.DSG_GATHER_TABLE.TABLE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return DsgGatherTable.DSG_GATHER_TABLE.TABLE_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return DsgGatherTable.DSG_GATHER_TABLE.COMMENT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field6() {
        return DsgGatherTable.DSG_GATHER_TABLE.CREATE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field7() {
        return DsgGatherTable.DSG_GATHER_TABLE.UPDATE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getGatherDbId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getTable_();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getTableName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getComment();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component6() {
        return getCreateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component7() {
        return getUpdateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getGatherDbId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getTable_();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getTableName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getComment();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value6() {
        return getCreateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value7() {
        return getUpdateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DsgGatherTableRecord value1(String value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DsgGatherTableRecord value2(String value) {
        setGatherDbId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DsgGatherTableRecord value3(String value) {
        setTable_(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DsgGatherTableRecord value4(String value) {
        setTableName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DsgGatherTableRecord value5(String value) {
        setComment(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DsgGatherTableRecord value6(Timestamp value) {
        setCreateTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DsgGatherTableRecord value7(Timestamp value) {
        setUpdateTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DsgGatherTableRecord values(String value1, String value2, String value3, String value4, String value5, Timestamp value6, Timestamp value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached DsgGatherTableRecord
     */
    public DsgGatherTableRecord() {
        super(DsgGatherTable.DSG_GATHER_TABLE);
    }

    /**
     * Create a detached, initialised DsgGatherTableRecord
     */
    public DsgGatherTableRecord(String id, String gatherDbId, String table, String tableName, String comment, Timestamp createTime, Timestamp updateTime) {
        super(DsgGatherTable.DSG_GATHER_TABLE);

        set(0, id);
        set(1, gatherDbId);
        set(2, table);
        set(3, tableName);
        set(4, comment);
        set(5, createTime);
        set(6, updateTime);
    }
}
